services:
  ia_sisyphus:
    hostname:         ia_sisyphus.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_sisyphus:latest
        -           ia_sisyphus:latest
        - innovanon/ia_sisyphus
        -           ia_sisyphus
    restart:          no
    logging:
      driver:         syslog   
